### ISSUE TITLE
seg fault with resnext

### ISSUE THREAD

**Issue by 7SK** [ROCmSoftwarePlatform/tensorflow#34] opened 2018-04-04 14:24 UTC
Steps:
cd ~ && git clone https://github.com/wenxinxu/ResNeXt-in-tensorflow
pip install opencv-python pandas 
cd ~/ResNeXt-in-tensorflow/
python cifar10_train.py --version=’test’ --nois_use_ckpt

After moving tf.nn.conv2d @ https://github.com/wenxinxu/ResNeXt-in-tensorflow/blob/master/resNeXt.py#L93 to cpu, it is working

[bt.txt](https://github.com/ROCmSoftwarePlatform/tensorflow/files/1876171/bt.txt)

**Comment by whchung** [comment] 2018-04-04 14:27
@7SK thanks for providing the info for tracking. To my understanding you are looking into the issue. From the stacktrace it shares the same trait with most of other segfault issues we have now ( #16 / #21 / #23 / #34 ).

Please try `git pull`. I've made some few commits in `rocm-v1` branch which allows we build with `-c dbg` so you can monitor the process within `gdb`.

**Comment by whchung** [comment] 2018-04-05 21:32
crash behavior shows it's the same as #21

**Comment by whchung** [comment] 2018-04-07 00:45
+ @bensander @scchan @pfultz2 @dagamayank for awareness.

The root cause has been figured out. Multiple instances of `libunwind` are loaded at runtime and messed up the exception handling routine. Need to disable `libunwind` dependency across various components within ROCm stack.

**Comment by whchung** [comment] 2018-04-09 14:07
The issue would be resolved in the next ROCm 1.7.2 release where all `libunwind` dependencies be dropped. We will also publish a new set of PIP wheels.

**Comment by whchung** [comment] 2018-04-30 14:34
@7SK Since 1.7.2 has been released and to my understanding you've verified the issue in this ticket is no more I'm closing this issue hereby.

**Closed by whchung** 2018-04-30 14:34 UTC
Labels: bug, hcc, miopen integration
